# ルール一覧を表示
#- colon
#- control_statement
#- file_length
#- force_cast
#- function_body_length
#- leading_whitespace
#- line_length
#- nesting
#- operator_whitespace
#- return_arrow_whitespace
#- todo
#- trailing_newline
#- variable_name_max_length
#- variable_name_min_length
#- type_body_length
#- variable_name

# 一行の文字列制限を100文字から300文字に変更
line_length: 300

included:
- andFactoryTestApp

excluded: # Lint対象から外すファイルのあるパスを記述
- Pods
- AndFactoryTestAppTests
- AndFactoryTestAppUITests

# 無効にするルール
disabled_rules:
- trailing_whitespace # 余分に改行がある方が視認性が上がる為、無効
- type_name # クラス名は長くして情報を詰めておく必要もある為、無効
- identifier_name
- force_cast
- force_try
- switch_case_alignment
- unused_optional_binding
- cyclomatic_complexity
- file_length
- shorthand_operator

opt_in_rules:
- anyobject_protocol
#- array_init mapでも直感的
#- attributes @objc funcを許可したい
- capture_variable
- closure_body_length
- closure_end_indentation
- closure_spacing
- collection_alignment
- conditional_returns_on_newline
- contains_over_filter_count
- contains_over_filter_is_empty
- contains_over_first_not_nil
- contains_over_range_nil_comparison
#- convenience_type
- discarded_notification_center_observer
- discouraged_assert
- discouraged_none_name
#- discouraged_object_literal # オブジェクトリテラルを使いたいため
- discouraged_optional_boolean
- discouraged_optional_collection
- empty_collection_literal
#- empty_count >0の方が直感的なので
- empty_string
- empty_xctest_method
- enum_case_associated_values_count
- expiring_todo
#- explicit_acl # できる限りACLを省略したいため
#- explicit_enum_raw_value # ローバリューを省略することもあるため
- explicit_init
#- explicit_self # 関数は `self.` を付けずに呼び出したいため
#- explicit_top_level_acl # できる限りACLを省略したいため
#- explicit_type_interface # できる限り型推論したいため
#- extension_access_modifier # 省略することもある
- fallthrough
- fatal_error_message
#- file_header # このルールの意味を理解していないため
#- file_name
- file_name_no_space
- file_types_order
- first_where
- flatmap_over_map_reduce
- force_unwrapping
- function_default_parameter_at_end
- identical_operands
#- indentation_width
#- implicit_return クロージャ以外の通常メソッドにも適用されてしまうのでOFFにする
- implicitly_unwrapped_optional
- joined_default_parameter
- last_where
- legacy_random
- legacy_multiple
- legacy_objc_type
#- let_var_whitespace # 空白行を設けたくないこともあるため
- literal_expression_end_indentation
- lower_acl_than_parent
- missing_docs
- modifier_order
#- multiline_arguments # 引数は同じ行に2つ入れたいこともあるため
#- multiline_arguments_brackets # 括弧で行を増やしたくないため
#- multiline_function_chains # 関数の呼び出しは同じ行に2つ入れたいこともあるため
#- multiline_literal_brackets # 括弧で行を増やしたくないため
#- multiline_parameters # 引数は同じ行に2つ入れたいこともあるため
#- multiline_parameters_brackets # 括弧で行を増やしたくないため
- nimble_operator
#- no_extension_access_modifier # エクステンションにACLを設定したいことがあるため
#- no_grouping_extension # グループ化するためにエクステンションを使わないため
- nslocalizedstring_key
#- number_separator # 数字を `_` で区切りたくないため
#- object_literal # リテラルで生成したくないこともあるため
- operator_usage_whitespace
- optional_enum_case_matching
- overridden_super_call
- override_in_extension
- pattern_matching_keywords
#- prefixed_toplevel_constant # 定数のプリフィックスに `k` を付けたくないため
#- private_action
#- private_outlet
#- prohibited_interface_builder # ストーリーボードを使ってビューを生成したいため
- prohibited_super_call
- quick_discouraged_call
- quick_discouraged_focused_test
- quick_discouraged_pending_test
- redundant_nil_coalescing
- redundant_type_annotation
#- required_deinit # できる限りデイニシャライザを省略したいため
- required_enum_case
- single_test_class
- sorted_first_last
#- sorted_imports # インポート文をアルファベット順以外に並び替えたいこともあるため
- static_operator
- strict_fileprivate
#- strong_iboutlet # `@IBOutlet` を `weak` で定義したいこともあるため
#- switch_case_on_newline
#- toggle_bool
#- trailing_closure 警告が謎
- unavailable_function
- unneeded_parentheses_in_closure_argument
- unowned_variable_capture
- untyped_error_in_catch
- unused_declaration
- unused_import
- unused_private_declaration
- vertical_parameter_alignment_on_call
#- vertical_whitespace_between_cases # Switch文のケース間に空白行を設けたくないこともあるため
#- vertical_whitespace_closing_braces # 中括弧を閉じる前に空白行を設けたいことがあるため
#- vertical_whitespace_opening_braces # 中括弧を開く前に空白行を設けたいことがあるため
- xct_specific_matcher
- yoda_condition


# クラスの行数
type_body_length:
- 500 # warning
- 3000 # error

# 変数名の最大文字数
variable_name_max_length:
- 60 # warning
- 80 # error

# 変数名の最小文字数
variable_name_min_length:
- 1 # warning
- 0 # error

# 関数の長さ
function_body_length:
- 100 # warning
- 300 # error

# ファイル行数
file_length:
- 5000 # warning
- 10000 # error

# closureの行数
closure_body_length:
- 100 # warning
- 200 # error
